# Admin login credentials
[admin]
username = "admin"
password = "admin123"

# MySQL connection (optional if not using DB)
[mysql]
host = "localhost"
user = "root"
password = "Sarbajit@MySQL"
db = "cv"
